### ISSUE TITLE
Flashing LED on QL-500

### ISSUE THREAD

**Issue by splitbrain** [pklaus/brother_ql_web#1]
I'm trying to use this interface to create a label on my Brother QL-500 but all that happens is that the green LED is flashing.

Here's what happens when I use the label designer:

```
127.0.0.1 - - [16/Dec/2016 17:46:13] "GET /api/preview/text/test?font_family=Arial&font_size=70 HTTP/1.1" 200 1734
WARNING:brother_ql.raster:Trying to switch the operating mode on a printer that doesn't support the command.
WARNING:brother_ql.raster:Trying to switch the operating mode on a printer that doesn't support the command.
WARNING:brother_ql.raster:Trying to call add_autocut with a printer that doesn't support it
WARNING:brother_ql.raster:Trying to call add_cut_every with a printer that doesn't support it
WARNING:brother_ql.raster:Trying to set expanded mode (dpi/cutting at end) on a printer that doesn't support it
WARNING:brother_ql.raster:Trying to set compression on a printer that doesn't support it
INFO:brother_ql.raster:raster_image_size: 720x90
127.0.0.1 - - [16/Dec/2016 17:46:18] "GET /api/print/text/test?font_family=Arial&font_size=70 HTTP/1.1" 200 42172
```

The server was started with:

``./brother_ql_web.py --model QL-500 --loglevel DEBUG file:///dev/lp/printers/usb-Brother_QL-500_F4Z731433``

Anything I can do to help debugging this?

**Comment by pklaus** [comment]
Hi @splitbrain and thanks for reporting the issue.

If you start `brother_ql_web.py` with `--loglevel DEBUG`, it will not print but save the label to a file instead: `sample-out.png`. I should make that more clear in the README / CLI `--help`.

If you were trying without the DEBUG mode before, it should have worked. If it doesn't, please make sure, you are using the right labels. Currently `brother_ql_web` only work with 62mm continuous labels. Secondly, check that you are using an up-to-date version of brother_ql (`pip install --upgrade brother_ql`).

**Comment by splitbrain** [comment]
Yeah I tried without DEBUG before with the same result. However I'm using 62x29 labels.

**Comment by pklaus** [comment]
That's the problem. I didn't spend enough development effort so far on it to make it work with different label sizes. I want to add this some day though.

**Comment by pklaus** [comment]
I added initial support for different label types in commit c8b3c50. Please get the latest version and check again.

**Comment by pklaus** [comment]
Now die-cut labels will automatically have centered text (commit b59f981).
