### ISSUE TITLE
Reflect font-selection in frontend

### ISSUE THREAD

**Issue by vonloxley** [pklaus/brother_ql_web#11]
Not sure how this was supposed to work, but I needed the following in views/labeldesigner.jinja2" line 54:
`<option {% if label['DEFAULT_FONTS']['style'] == font_style and label['DEFAULT_FONTS']['family'] == font_family_name %}selected{% endif %}>{{font_family_name}} ({{ font_style }})</option>`

**Comment by ChristopherHackett** [comment]
Thanks @vonloxley for the hint, much appreciated.

**Comment by pklaus** [comment]
Fix finally cherry-picked and pushed. Thanks!
