### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by jmcwhirter** [pklaus/brother_ql_web#18]
- OS: Mac Sierra
- Language: Python 3

I can't start the web server with no parameters, per the instructions. I also cannot start the server when I supply a font-folder parameter. Same error.

```
deprecation warning: brother_ql.devicedependent is deprecated and will be removed in a future release
Traceback (most recent call last):
  File "./brother_ql_web.py", line 296, in <module>
    main()
  File "./brother_ql_web.py", line 271, in main
    FONTS = get_fonts()
  File "/Users/justindm/Development/printer/brother_ql_web/font_helpers.py", line 25, in get_fonts
    styles = parts[2].split('=')[1].split(',')
IndexError: list index out of range
```

I manually run `fc-scan --format "%{file}:%{family}:style=%{style}\n" /my/directory/Fonts` and get about 40 lines.

**Comment by ukmattbrock** [comment]
I had this as well.. got a pull request to handle it..

https://github.com/pklaus/brother_ql_web/pull/24

**Comment by pklaus** [comment]
Thanks for reporting this. Sorry it took me so long to fix it.
