### ISSUE TITLE
RED FLASHING LED on QL-800

### ISSUE THREAD

**Issue by xDsquare** [pklaus/brother_ql_web#22]
Whenever I try to print at the correct format (29mm endless) the LED starts flashing red and nothing happens while the web-interface says "Printing was successful". 

```
sudo ./brother_ql_web.py --loglevel DEBUG
...
Bottle v0.12.16 server starting up (using WSGIRefServer())...
Listening on http://:8013/
Hit Ctrl-C to quit.

127.0.0.1 - - [10/May/2019 21:53:38] "POST /api/preview/text?return_format=base64 HTTP/1.1" 200 404
127.0.0.1 - - [10/May/2019 21:53:39] "POST /api/preview/text?return_format=base64 HTTP/1.1" 200 632
127.0.0.1 - - [10/May/2019 21:53:40] "POST /api/preview/text?return_format=base64 HTTP/1.1" 200 632
DEBUG:brother_ql.raster:raster_image_size: 720x107
DEBUG:brother_ql.backends.generic:Writing 10195 bytes.
127.0.0.1 - - [10/May/2019 21:53:41] "POST /api/print/text HTTP/1.1" 200 17
```

My config.json:
```
{
  "SERVER": {
    "PORT": 8013,
    "HOST": "",
    "LOGLEVEL": "WARNING",
    "ADDITIONAL_FONT_FOLDER": false
  },
  "PRINTER": {
    "MODEL": "QL-800",
    "PRINTER": "usb://04f9:209b/000H8Z203810"
  },
  "LABEL": {
    "DEFAULT_SIZE": "29",
    "DEFAULT_ORIENTATION": "standard",
    "DEFAULT_FONT_SIZE": 5,
    "DEFAULT_FONTS": [
      {"family": "Minion Pro",      "style": "Semibold"},
      {"family": "Linux Libertine", "style": "Regular"},
      {"family": "DejaVu Serif",    "style": "Book"}
    ]
  },
  "WEBSITE": {
    "HTML_TITLE": "Label Designer",
    "PAGE_TITLE": "Brother QL Label Designer",
    "PAGE_HEADLINE": "Design your label and print it…"
  }
}

```

I'm thankful for every help!

**Comment by Bansher** [comment]
I have the same kind of problem. There is a solution?

**Comment by Bansher** [comment]
> I have the same kind of problem. There is a solution?
https://github.com/PaintSplasher/unifi-voucher-service/issues/5

**Comment by kennedybaird** [comment]
Any update on this anyone? I'm having troubles with QL-800 as well.

**Comment by Mikhail5555** [comment]
I am using a QL-800 and it works for me

**Comment by pklaus** [comment]
It's been a long time. Sorry!

I've improved the compatibility of brother_ql_web with the QL-800 series a lot with the commits 2b5902a and 6da0745. Please check again. If any problem persists, could you please report:

* output of `brother_ql info env`
* which exact label roll type is in the printer
* which label roll type did you select in the web GUI or on the command line

I'll close this issue for now but if you have any further problem with the QL-800 series / red flashing LEDs, feel free to reopen this issue or open a new issue with the information requested above.

**Comment by dadosch** [comment]
Ok, so in case it's unclear for some: You have to select "62mm endless (Black/Red/White)".

By the way, how does it work? I thought the black color would appear because of heat, but how does it distinguish between black and red?

**Comment by mikhail5555** [comment]
> Ok, so in case it's unclear for some: You have to select "62mm endless (Black/Red/White)".
> 
> By the way, how does it work? I thought the black color would appear because of heat, but how does it distinguish between black and red?

Short exposure: Red
Long exposure: Black (Or more purpleishe colour)

**Comment by nmlpg12** [comment]
i am sorry for dropping by but i haven't been able to print through the web icons. it doesn't do anything just stall printing but doesn't print or gives error code. i am a littlebit frustrated need help

**Comment by s00500** [comment]
One more note for everyone else playing with the default labels, the small roll that usually comes with it is a 29x90 DIE-CUT , and NOT a 29 endless (Since that just cost me 15 minutes of confusion =D) Thanks for the awesome project!!!!

**Comment by 395Tech** [comment]
Ok I can print red text if I select "62mm endless (black/red/white)".  But I don't want to print in red.  I just want to print normal black.
