### ISSUE TITLE
CR from browser address field

### ISSUE THREAD

**Issue by joppana** [pklaus/brother_ql_web#23]
http://www.yotime.fi:8013/api/print/text?text=Matti Meik%C3%A4l%C3%A4inen\nTrackCode\n12345678901&font_size=50&font_family=Caladea(Regular)

Trying to add return for the label. Liked
Meikäläinen
TrackCode
12345678901

now everyone goes to one line. So, how to add line Break?

**Comment by pklaus** [comment]
Just use `%0A` (newline) instead of `%C3` (carriage return).
Best, Phil
