### ISSUE TITLE
QL-820NWB @62mm endless does not work

### ISSUE THREAD

**Issue by tobit6795** [pklaus/brother_ql_web#35]
tested the following container

```
docker run \
  --name brother_ql_web \
  --detach \
  --publish 8013:8013 \
  --restart=always \
  pklaus/brother_ql_web:latest \
  ./brother_ql_web.py --model QL-820NWB tcp://192.168.0.57
```

endless does not appear to work, printer led flashes orange, but 62mm **red** is working lol

**Comment by pklaus** [comment]
I suppose you're using the default label roll that comes with the device when you purchase it? That's a one which can print black and red on white, so you **have** to choose "62mm red" if you want to print on that one.

**Comment by tobit6795** [comment]
yes i use the default label roll. okay but how can i switch colour in this case ?

![grafik](https://user-images.githubusercontent.com/31254099/106368862-48cda380-634d-11eb-8c92-5b571ff0520b.png)

i expected sth to be under font settings ...

**Comment by pklaus** [comment]
Printing black text on the "62mm red" label is currently not implemented in the web interface of `brother_ql_web`. Feel free to add a pull request, for example with an additional option black/red font color in the "Font Settings" section.

**Comment by pklaus** [comment]
BTW: A quick fix to simply print black whatever label size is selected: edit [line 79 of brother_ql_web.py](https://github.com/pklaus/brother_ql_web/blob/9e20b6d/brother_ql_web.py#L79):

```py
    context['fill_color']  = (255, 0, 0) if 'red' in context['label_size'] else (0, 0, 0)
```

and change it to:

```py
    context['fill_color']  = (0, 0, 0)
```
