### ISSUE TITLE
MACOS fonts not found

### ISSUE THREAD

**Issue by MoD01** [pklaus/brother_ql_web#4]
I am using macOS and get this error : 

``` No such file or directory: 'fc-list'```.

**Comment by pklaus** [comment]
Hi MoD01,

sorry for the late reply. `fc-list` is a command line tool that comes with [fontconfig](https://www.freedesktop.org/wiki/Software/fontconfig/). This can be installed on Mac OS X / "Mac OS" with Homebrew:

1. Install Homebrew if not done so already: <https://brew.sh/>
2. Install fontconfig: <http://brewformulas.org/Fontconfig>

Hope this helps. And thanks for the bug report. It reminds me I should mention this requirement in the README.

**Comment by pklaus** [comment]
In 02d69f6 I mentioned fontconfig in the requirements and in c455a9e it was further clarified. Thanks again for filing this bug report.

**Comment by jdhao** [comment]
> In [02d69f6](https://github.com/pklaus/brother_ql_web/commit/02d69f613ad7ba9fa657f8a96153120ae02b40c8) I mentioned fontconfig in the requirements and in [c455a9e](https://github.com/pklaus/brother_ql_web/commit/c455a9e42886ed19e99f1e32e1a4e8d43a202c83) it was further clarified. Thanks again for filing this bug report.

The fontconfig formula URL is invalid and has been changed to https://formulae.brew.sh/formula/fontconfig#default.
