### ISSUE TITLE
Font Alignment via API

### ISSUE THREAD

**Issue by timnijland3** [pklaus/brother_ql_web#44]
Is there a way to do the Font Alignment via the API aswell?

I tried:
`"font_alignment" => "left",`

But that wasn't working.

**Comment by FriedrichFroebel** [comment]
According to https://github.com/pklaus/brother_ql_web/blob/9e20b6dc3f80589bffc0b1036aa3f7122ea4af89/views/labeldesigner.jinja2#L147

you will have to use the `align` key with either `left`, `center` or `right` as the value.
